# -*- coding: utf-8 -*-
"""
/***************************************************************************
 vgle
                                 A QGIS plugin
 This plugin groups framgented poylgons together.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-01
        copyright            : (C) 2024 by GOPA
        email                : gudmandras@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys, os, pathlib, glob
sys.dont_write_bytecode = True

def classFactory(iface): 
    """Load vgle class from file vgle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .polygon_grouper import vgle
    pycFiles = glob.glob(os.path.dirname(os.path.abspath(__file__)) + "/*.pyc", recursive=True)
    for pycFile in pycFiles:
        if os.path.isfile(pycFile):
            os.remove(pycFile)
    return vgle(iface)
